### ISSUE TITLE
What's the difference between this repository and https://github.com/gwsw/less

### ISSUE THREAD

**Issue by jpluimers** [rivy/less#3]
It seems the canonical repository is https://github.com/gwsw/less

Two questions:

- How does it differ from your repository?
- Why is your repository not a fork?

**Comment by rivy** [comment]
I "forked" it from source archives about 6 years ago (starting with v418) to improve the Windows story. Primarily, I made compilation improvements for MSVC and `gcc` (and recently `clang`), a few bugfixes, and expanded ANSI color support. I offered the improvements to Nudelman via email a few years ago, but he never responded.

So, I ultimately pushed it from my private repo to a public github repo a couple of years ago.

I've been intermittently merging in source updates from the releases at <http://greenwoodsoftware.com/less/index.html> when it seems appropriate. 

This is the first I've heard about Nudelman publishing a publicly source repository.

**Comment by jpluimers** [comment]
Thanks. 

Is it OK for you that I open a new issue for you to start merging your changes into the main source repository? 

I know it will be manual labour, but I think it is important to try to push changes to the ultimate source.

**Comment by rivy** [comment]
Hmm, I'm not opposed to the idea. But, I don't see much of any non-gwsw activity on the [gwsw/less repository](https://github.com/gwsw/less) (perhaps, it's just a mirror?). And given the lack of prior response, I'm hesitant to put any work into teasing out my changes just to be ignored again.
