### ISSUE TITLE
Follow-Up for Blank Output 

### ISSUE THREAD

**Issue by jimfoltz** [rivy/less#4]
In reference to https://github.com/gwsw/less/issues/10

So far, so good.

Tools
* Windows 10 Home x64 v1903
* `Makefile.win.mingw`
* `GNU Make 4.2.1 built for Windows32`
* `gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0`
* make & gcc installed with [scoop](https://github.com/lukesampson/scoop)

Thanks

**Comment by rivy** [comment]
I'm happy to have helped!
